language: node_js
sudo: required

services:
  - docker

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESS_KEY
  secret_access_key:
    secure: $SECRET_ACCESS_KEY
  region: "us-east-2"
  app: "ip_assessment"
  env: "ipassessment-env"
  bucket_name: "theholygoatz"
  on:
    branch: CI/CD